language: ruby
rvm:
  - 2.2.0
sudo: false
script: bundle exec rake deploy

env:
  global:
    secure: o47/BGfWSaIL9bv++KFO8InnHjX98i1JYhTw+XrNtb1xK/Kozc3GGkIcPUGHDzJwU2pNkRAPvXUDmaKINxJYaN+f66coZO9boNk/YBs5w2iLWwm2GdbBdYkEpMfoqo2QodoWb2THM1vps1u99jo4gspcHNeDi+FSUb/YQIUYvE1djR2oyxVnO2SxTBbwdflBLAgsttVRsPZTnhS0nN0r09gjQSy6xRGMOaza2pMoGyTY7MexisStbQWOUu7ntp4ukLIW/aFriWQSTU1k8QeiKeIvHCs6b/DEnFQS2UfiojeHodcEHrZ6/RHcN5+ZyFdYB9jZPJfS/FQKHxFtvxCAM/ArfdGrSbVqpbuOGBrp3/Yj6n3ui9hK38buPedL/V0ov7sgF9q3wemxBSrr/+IPekD3ZXuoxtyXuK4TtLpkzSsAgB4fNlIAopHKbyIZQpCMrID5ErKceEvxXl5yVSeuF30otC4m7pWcXVlmg1K7rQnlEQayuf2l65KRBnt/zKAjshNrrvtUowEsjxZWYXw1eodHKhjMtDKIMuTa20b5DbB0Uq2Vx0S35Y3FbJ0YUkH5pIQXri1mx4UyVIJemE3ueUBHOcV+mYk5AoMpbbS4DQkESQB35MuuwGTOPsaCdXhG0V/omYp9jp6rNkXktnpaLhNm+XHxB2zYVnad7JetB6U=
